name: Mermaid

on:
  push:
    paths:
      - '**.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Mermaid CLI
        run: npm install -g @mermaid-js/mermaid-cli
        
      - name: Build Mermaid Diagrams
        run: |
          find . -name "*.md" -type f -exec sh -c '
            for file do
              mmdc -i "$file" -o "${file%.md}.png"
            done
          ' sh {} +
          
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Generate Mermaid diagrams" || echo "No changes to commit"
          git push 